module.exports = {
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  semi: false,
  singleQuote: false,
  quoteProps: "as-needed",
  bracketSpacing: true,
  trailingComma: "none",
  arrowParens: "always",
  insertPragma: false,
  requirePragma: false,
  proseWrap: "never",
  endOfLine: "lf",
};
